(() => {
'use strict';
const ISF = window.ISF;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={people:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M16 3a4 4 0 0 1 0 8 M22 21v-2a4 4 0 0 0-3-3.87 M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',building:'M4 22V3h12v19 M16 10h5v12 M2 22h21 M8 7h1 M12 7h1 M8 11h1 M12 11h1 M8 15h1 M12 15h1 M9 22v-4h3v4',compass:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M16 8l-3 5-5 3 3-5z',drop:'M12 2C10 6 4 11 4 15a8 8 0 0 0 16 0c0-4-6-9-8-13z M8 15a4 4 0 0 0 4 4',waves:'M2 6q3-3 6 0t6 0 8 0 M2 12q3-3 6 0t6 0 8 0 M2 18q3-3 6 0t6 0 8 0',tank:'M4 5c0-4 16-4 16 0s-16 4-16 0 M4 5v14c0 4 16 4 16 0V5 M4 13c0 4 16 4 16 0',tool:'M14 6a6 6 0 0 0-7 7L2 18a3 3 0 0 0 4 4l5-5a6 6 0 0 0 7-7l-4 4-4-4z',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0 M15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0',check:'M20 6L9 17l-5-5 M21 12v8H3V3h12',search:'M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0 M15 15l7 7',ruler:'M3 16L16 3l5 5L8 21z M7 12l3 3 M11 8l3 3 M15 4l3 3',chart:'M3 3v18h19 M7 17v-5 M12 17V7 M17 17V3',file:'M14 2H5v20h14V7z M14 2v6h5 M8 12h8 M8 16h8',book:'M12 5v17 M12 5C7 1 2 3 2 3v16s5-2 10 3c5-5 10-3 10-3V3s-5-2-10 2',heart:'M20 4c-3-3-6-1-8 1C10 3 7 1 4 4c-4 4 0 9 8 16 8-7 12-12 8-16z',money:'M2 5h20v14H2z M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0 M5 9h1 M18 15h1',school:'M2 8l10-6 10 6-10 6z M5 10v8c4 3 10 3 14 0v-8 M22 8v9',link:'M10 13a5 5 0 0 0 7 0l4-4a5 5 0 0 0-7-7l-2 2 M14 11a5 5 0 0 0-7 0l-4 4a5 5 0 0 0 7 7l2-2'};
function icon(name){return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.compass}"/></svg>`}
const sequence=['inicio','intervencion','comunidad','isf','empresas','ciclo','definido','resultados'];
const labels={inicio:'Programa',intervencion:'Intervención n',comunidad:'Comunidad',isf:'ISF Chile',empresas:'Empresas',ciclo:'Ciclo de intervención',definido:'Selección progresiva',resultados:'Resultados'};
let view='inicio',stage=0,selected='desafios',example=false,cycleParent='intervencion',resultsParent='intervencion';
function node(id,title,ico,x,y,cls='',sub=''){return `<button class="node ${cls}" data-go="${id}" style="left:${x}%;top:${y}%">${icon(ico)}<strong>${title}</strong>${sub?`<small>${sub}</small>`:''}</button>`}
function renderPageHeading(eyebrow,title,desc,extra=''){return `<div class="page-top"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p class="lead">${desc}</p></div>${extra}</div>`}
function home(){return `<div class="home"><section><span class="eyebrow">ISF Chile · Banco de Proyectos</span><h1>${ISF.nombre}</h1><p class="lead">Un proceso técnico y comunitario para construir soluciones pertinentes, viables y sostenibles.</p><div class="metrics"><div class="metric"><strong>36</strong><span>meses de programa</span></div><div class="metric"><strong>5</strong><span>regiones de intervención</span></div><div class="metric"><strong>1.920</strong><span>meta de beneficiarios directos</span></div></div><div class="inline-links"><button class="text-link" data-modal="alcance">Ver alcance y recursos</button><button class="results-shortcut" data-go="resultados">Resultados esperados <span aria-hidden="true">↗</span></button></div></section><section class="universe"><div class="universe-title"><span class="big-number">12</span><div><h2>intervenciones</h2><small>4 por año · una metodología común</small></div></div>${[1,2,3].map(a=>`<div class="year"><span>AÑO ${a}</span>${[1,2,3,4].map(n=>`<button class="intervention-dot" data-go="intervencion" aria-label="Explorar la metodología de la intervención ${(a-1)*4+n}">${icon('people')}<span>${String((a-1)*4+n).padStart(2,'0')}</span></button>`).join('')}</div>`).join('')}<p class="small">Selecciona una intervención para explorar cómo funciona. Las comunidades se definen durante el programa.</p></section></div>`}
function intervention(){return `${renderPageHeading('Del programa al territorio','Una intervención, tres actores','La comunidad aporta su conocimiento local; ISF articula el proceso; las empresas suman recursos y experiencia especializada.')}<div class="orbit main-orbit"><svg class="orbit-lines" viewBox="0 0 1000 505" preserveAspectRatio="none"><path d="M220 182L500 238L780 182 M500 238L500 384 M220 182L100 75 M220 182L110 313 M780 182L900 75 M780 182L890 313 M500 384L325 424 M500 384L675 424"/></svg>${node('comunidad','Comunidad','people',22,36,'','Ver su territorio')}${node('empresas','Empresas','building',78,36,'','Ver sus aportes')}${node('isf','ISF Chile','compass',50,76,'','Ver el equipo')}${node('ciclo','Intervención de ingeniería humanitaria','tool',50,38+9,'center','Explorar el ciclo')}<span class="bubble large local" style="left:10%;top:15%">Conocimiento<br>local</span><button class="bubble challenge" style="left:11%;top:62%" data-go="comunidad">Desafío<br>comunitario</button><span class="bubble large tech" style="left:90%;top:15%">Conocimiento<br>técnico</span><span class="bubble orange money" style="left:89%;top:62%">Financiamiento</span><span class="bubble method" style="left:32.5%;top:84%">Metodología</span><span class="bubble medium isf-tech" style="left:67.5%;top:84%">Conocimiento<br>técnico</span></div>`}
const info={
 comunidad:{title:'La comunidad conoce el territorio',desc:'Su conocimiento local orienta las decisiones. La necesidad, las condiciones de elegibilidad y las redes del territorio se examinan por separado.',ico:'people',core:'Comunidad',resource:['Recurso fundamental','Conocimiento local','saberes'],groups:[
  {id:'desafios',title:'Problemática',subtitle:'Qué ocurre con el agua y el saneamiento',ico:'drop',children:ISF.desafios.map(d=>[d.id,d.titulo,d.icono])},
  {id:'elegibilidad',title:'Criterios de elegibilidad',subtitle:'Condiciones que deben cumplirse simultáneamente',ico:'check',children:[['organizacion','Organización y disposición','people'],['vulnerabilidad','Vulnerabilidad y carencia','search'],['legal','Viabilidad legal inicial','file']]},
  {id:'territorio',title:'Actores y condiciones locales',subtitle:'Redes y recursos que habilitan el trabajo',ico:'pin',children:[['municipio','Municipio y servicios','building'],['redes','Fundaciones y otras redes','heart'],['habilitantes','Condiciones para implementar','compass']]}
 ]},
 isf:{title:'ISF conecta el territorio y la ingeniería',desc:'Un equipo con responsabilidades definidas, experiencia institucional y una metodología común sostienen cada intervención.',ico:'compass',core:'ISF Chile',groups:[
  {id:'equipo',title:'Equipo',subtitle:'Quién conduce y quién aporta al trabajo',ico:'people',children:[['direccion','Dirección y gestión','compass'],['coordinador','Coordinación territorial','pin'],['voluntarios','Voluntariado y practicantes','people'],['mentores','Mentores profesionales','school']]},
  {id:'experiencia',title:'Experiencia institucional',subtitle:'Antecedentes que respaldan la capacidad de ejecución',ico:'chart',children:[]},
  {id:'metodologia',title:'Metodología',subtitle:'Ingeniería para el desarrollo sostenible',ico:'compass',go:'ciclo',children:[]}
 ]},
 empresas:{title:'Las empresas aportan capacidades',desc:'Los recursos financieros y la experiencia profesional se integran al proceso de trabajo que ISF desarrolla junto a la comunidad.',ico:'building',core:'Empresas',groups:[
  {id:'financiamiento',title:'Financiamiento',subtitle:'Recursos para el proceso completo',ico:'money',children:[]},
  {id:'mentoria_tecnica',title:'Mentoría y conocimiento técnico',subtitle:'Un mismo aporte: experiencia profesional especializada',ico:'school',children:[]},
  {id:'colaboracion',title:'Articulación con ISF',subtitle:'Cómo se conectan los aportes con el territorio',ico:'link',children:[]}
 ]}
};
const details={
 saberes:['Conocimiento local','Las personas conocen los usos del agua, la historia de las fallas, la organización y las condiciones del lugar.',['Ayudan a distinguir síntomas y causas.','Aportan prácticas, recursos y prioridades de la comunidad.','Participan en la comparación y validación de alternativas.'],'El saber local se integra al conocimiento técnico durante el diagnóstico y el diseño.'],
 organizacion:['Organización y participación','Una contraparte local identificable debe estar dispuesta a trabajar durante el proceso.',['Puede ser una junta de vecinos, comité de agua, establecimiento educacional u otra organización formal.','Participa en el diagnóstico, diseño e implementación.','Se promueve la participación representativa de mujeres en el diseño y las decisiones.','Se definen responsables y un plan de operación y mantenimiento.'],'La sostenibilidad se construye con la comunidad desde el inicio.'],
 municipio:['Municipio y servicios territoriales','Facilitan la identificación de necesidades y el acceso a antecedentes del territorio.',['Municipios y SLEP pueden vincular a ISF con posibles comunidades.','Aportan antecedentes para verificar vulnerabilidad y carencias.','La coordinación con autoridades y servicios depende de los permisos y condiciones de cada intervención.'],'Forman parte de la red de apoyo; la comunidad conserva su papel en las decisiones.'],
 redes:['Fundaciones y otras redes','Organizaciones sociales, universidades e instituciones locales conectan necesidades con capacidades.',['Ayudan a identificar potenciales comunidades.','Comparten antecedentes y conocimiento del territorio.','Pueden facilitar vínculos y coordinación para el trabajo conjunto.'],'Su participación concreta depende del territorio y se define para cada intervención.'],
 coordinador:['Una coordinación por intervención','Cada coordinador o coordinadora territorial lidera una intervención a la vez y dedica 45 horas mensuales.',['Coordina la comunidad, el equipo técnico y los actores locales.','Gestiona cronograma, recursos y equipos de voluntariado.','Lidera diagnóstico, diseño e implementación en terreno y elabora informes.'],'El programa considera cuatro coordinaciones: dos en RM, una para Coquimbo–Valparaíso y una para Biobío–Araucanía.'],
 voluntarios:['Entre 4 y 8 personas por proyecto','Practicantes y voluntarios aportan trabajo técnico en terreno, acompañados por la coordinación territorial.',['Reclutamiento principalmente desde universidades con convenio activo con ISF.','Perfil técnico pertinente para las tareas de la intervención.','Carta de compromiso firmada al inicio del proyecto.','Inducción y capacitación antes de cada intervención.'],'El voluntariado trabaja dentro de una estructura de coordinación y responsabilidades.'],
 mentores:['Experiencia profesional al servicio del proyecto','Ingenieros e ingenieras con experiencia, provenientes principalmente de empresas aliadas.',['Aportan conocimiento especializado durante el diseño.','Ayudan al equipo a analizar alternativas y fortalecer sus propuestas.','Trabajan junto a voluntarios, coordinación e integrantes de la comunidad.'],'Su aporte se conecta con la necesidad identificada en terreno.'],
 direccion:['Dirección y gestión del programa','El equipo base organiza recursos, acompaña la ejecución y articula las alianzas.',['Dirección Ejecutiva · 90 h/mes: recursos, equipo, financiamiento y alianzas.','Dirección de Proyectos · 120 h/mes: alcance, riesgos, recursos, equipos y cierre.','Coordinación de Movimiento · 60 h/mes: convocatoria, comunicación y gestión del voluntariado.'],'Las cuatro coordinaciones territoriales cuentan con 45 h/mes cada una.'],
 experiencia:['Experiencia que respalda el método','El currículum institucional del formulario presenta antecedentes de ejecución y colaboración.',['Co-creando soluciones hídricas desde la ingeniería humanitaria · 2023–2025 · cobertura reportada de 3.776 personas.','AQUA365 · 2022–2025 · cobertura reportada de 3.300 personas.','Mejora de acceso y construcción de escalera · 2019 · cobertura reportada de 150 personas.'],'Las coberturas del CV incluyen población directa e indirecta. No se suman ni equivalen a beneficiarios directos únicos.'],
 financiamiento:['Financiar el proceso completo','Los recursos permiten evaluar, diseñar, implementar y verificar las intervenciones.',['Horas profesionales, visitas a terreno y trabajo comunitario.','Levantamientos técnicos y evaluación de prefactibilidad.','Materiales, contrataciones especializadas y capacitación para implementar la solución.'],'Programa: $284.400.000 totales; $264.400.000 solicitados en donaciones y $20.000.000 de aporte propio. No son montos comprometidos por una empresa específica.'],
 expertos:['Mentores profesionales expertos','Las empresas aliadas conectan la intervención con profesionales experimentados.',['Acompañan al equipo en el desarrollo de alternativas.','Comparten experiencia práctica para revisar decisiones técnicas.','Contribuyen a fortalecer el aprendizaje del voluntariado.'],'La coordinación de ISF integra la mentoría al proceso de trabajo comunitario.'],
 tecnica:['Conocimiento técnico especializado','La experiencia profesional amplía las capacidades disponibles para abordar el desafío.',['Se incorpora a partir de las necesidades que revela el diagnóstico.','Se combina con el conocimiento local de la comunidad.','Contribuye al análisis y refinamiento de propuestas durante el diseño participativo.'],'La tecnología y la solución se deciden después de comprender el problema.'],
 colaboracion:['Una colaboración articulada por ISF','ISF conecta los aportes de empresas con el equipo y las necesidades del territorio.',['La comunidad participa en la definición del desafío y la validación de alternativas.','El equipo de ISF conduce la metodología y coordina la ejecución.','Las empresas pueden aportar donaciones y profesionales con experiencia.'],'Los aportes se complementan dentro de una misma intervención.']
};
Object.assign(details,{
 vulnerabilidad:['Vulnerabilidad y carencia verificable','La comunidad debe presentar una situación de vulnerabilidad socioeconómica y una carencia relevante en servicios básicos.',[
 'La vulnerabilidad se acredita mediante antecedentes municipales, Registro Social de Hogares, información censal u otros instrumentos reconocidos por el Estado.',
 'La carencia se verifica con antecedentes territoriales y se confirma durante el levantamiento en terreno.',
 'El diagnóstico caracteriza a la población que recibirá directamente el beneficio.'
 ],'Las 160 personas por intervención son un promedio de planificación. No constituyen un mínimo de elegibilidad.'],
 legal:['Viabilidad legal inicial','Debe identificarse al propietario, administrador o institución responsable del terreno o infraestructura, sin impedimentos legales evidentes que hagan inviable intervenir.',[
 'La elegibilidad revisa si existen condiciones legales iniciales para avanzar.',
 'Los permisos y autorizaciones específicos se determinan según la solución seleccionada.',
 'Antes de implementar se conforma el expediente técnico y legal: autorización, antecedentes de propiedad o uso, descripción, presupuesto, croquis o planos y permisos aplicables.'
 ],'La revisión inicial y el expediente previo a la obra corresponden a momentos distintos del proceso.'],
 habilitantes:['Condiciones que habilitan la intervención','Además de la elegibilidad, la prefactibilidad examina los recursos y condiciones prácticas para ejecutar y sostener una solución.',[
 'Accesibilidad al territorio y traslado de materiales.',
 'Disponibilidad de información y coordinación con instituciones locales.',
 'Capacidad de operación y mantenimiento, costos y recursos disponibles.',
 'Riesgos naturales, climáticos u operacionales que puedan afectar la continuidad.'
 ],'Estas condiciones se evalúan en la prefactibilidad y la priorización de las comunidades.'],
 mentoria_tecnica:['La experiencia técnica se comparte mediante mentorías','Profesionales expertos de empresas aliadas aportan su conocimiento al equipo y al diseño participativo.',[
 'Ayudan a analizar y comparar alternativas frente al problema diagnosticado.',
 'Revisan decisiones técnicas y comparten experiencia práctica con el voluntariado.',
 'Contribuyen al refinamiento de propuestas junto a la coordinación y la comunidad.'
 ],'La mentoría es la forma de participación; el conocimiento técnico especializado es su aporte. Ambos se integran al saber local.']
});
function selectedGroup(){return info[view].groups.find(g=>g.id===selected||g.children.some(c=>c[0]===selected));}
function textDetail(id){const d=details[id];return `<span class="mini-label">${labels[view]} · ${selectedGroup()?.title||'Recurso fundamental'}</span><h2>${d[0]}</h2><p>${d[1]}</p><ul>${d[2].map(x=>`<li>${x}</li>`).join('')}</ul><p class="detail-note">${d[3]}</p>`;}
function openRows(items){return `<div class="open-rows">${items.map((r,i)=>`<button data-detail="${r[0]}"><span class="row-icon">${icon(r[2])}</span><span><strong>${r[1]}</strong>${r[3]?`<small>${r[3]}</small>`:''}</span><span class="row-arrow" aria-hidden="true">↗</span></button>`).join('')}</div>`;}
function detailContent(){
 if(selected==='desafios')return `<span class="mini-label">01 · Problemática</span><h2>Comprender el problema antes de elegir una solución</h2><p>Los desafíos de agua y saneamiento se investigan con la comunidad. Un mismo síntoma puede tener causas distintas.</p>${openRows(ISF.desafios.map(d=>[d.id,d.titulo,d.icono,d.resumen]))}<p class="detail-note">Estas situaciones ilustran lo que se investiga. El diagnóstico determina qué ocurre en cada comunidad.</p>`;
 if(selected==='elegibilidad')return `<span class="mini-label">02 · Criterios de elegibilidad</span><h2>Tres condiciones para avanzar</h2><p>La comunidad debe cumplir los tres requisitos. Si existe una restricción crítica que impide intervenir, se descarta la candidatura y se informa a las partes.</p>${openRows([['organizacion','Organización y disposición al trabajo conjunto','people','Una contraparte identificable y dispuesta a participar.'],['vulnerabilidad','Vulnerabilidad y carencia verificable','search','Antecedentes que acrediten la situación y la necesidad.'],['legal','Viabilidad legal inicial','file','Responsable del terreno o infraestructura identificado, sin impedimentos evidentes.']])}<p class="detail-note">La elegibilidad permite pasar a la prefactibilidad; todavía no define la obra.</p>`;
 if(selected==='territorio')return `<span class="mini-label">03 · Actores y condiciones locales</span><h2>El territorio también aporta capacidades</h2><p>Las redes locales ayudan a identificar necesidades, reunir antecedentes y coordinar el trabajo. La evaluación considera además las condiciones para implementar y sostener una solución.</p>${openRows([['municipio','Municipio y servicios territoriales','building','Vínculos, antecedentes y coordinación institucional.'],['redes','Fundaciones, universidades y otras redes','heart','Presencia local, conocimiento del territorio y colaboración.'],['habilitantes','Condiciones para implementar','compass','Accesibilidad, recursos, operación y riesgos.']])}`;
 if(selected==='equipo')return `<span class="mini-label">01 · Equipo</span><h2>Responsabilidades claras en cada intervención</h2><p>El equipo base gestiona el programa; la coordinación territorial conduce el trabajo en terreno y articula las capacidades que participan.</p><div class="team-tree"><button class="team-management" data-detail="direccion">${icon('compass')}<span><small>Gestión del programa</small><strong>Dirección y gestión</strong></span><span aria-hidden="true">↗</span></button><div class="team-spine" aria-hidden="true"></div><button class="team-coordinator" data-detail="coordinador">${icon('pin')}<span><small>Conducción en terreno · 45 h/mes</small><strong>Coordinación territorial</strong></span><span aria-hidden="true">↗</span></button><p class="team-relationship">Coordina el trabajo y articula los aportes de</p><div class="team-contributors"><button data-detail="voluntarios">${icon('people')}<strong>Voluntariado y practicantes</strong><small>4 a 8 personas por intervención</small></button><button data-detail="mentores">${icon('school')}<strong>Mentores profesionales</strong><small>Experiencia técnica especializada</small></button></div></div><p class="detail-note">Cada coordinación territorial lidera una intervención a la vez. El programa considera cuatro coordinaciones.</p>`;
 if(selected==='experiencia')return `<span class="mini-label">02 · Experiencia institucional</span><h2>Experiencia documentada</h2><p>El currículum de la postulación presenta antecedentes de ejecución y colaboración.</p><div class="experience-records">${[['2023–2025','Co-creando soluciones hídricas desde la ingeniería humanitaria','3.776'],['2022–2025','AQUA365','3.300'],['2019','Mejora de acceso y construcción de escalera','150']].map(r=>`<article><span class="record-year">${r[0]}</span><h3>${r[1]}</h3><p><strong>${r[2]}</strong> personas de cobertura reportada</p></article>`).join('')}</div><p class="detail-note">Fuente: currículum institucional del formulario. Las coberturas incluyen población directa e indirecta; no se suman ni representan personas únicas.</p>`;
 const challenge=ISF.desafios.find(d=>d.id===selected);if(challenge)return `<span class="mini-label">Problemática · Agua y saneamiento</span><h2>${challenge.titulo}</h2><p>${challenge.resumen}</p><ul>${challenge.detalles.map(x=>`<li>${x}</li>`).join('')}</ul><span class="mini-label">Qué se investiga</span><p>${challenge.investigar}</p><span class="mini-label">Qué podría medirse</span><p>${challenge.medir}</p>`;
 return textDetail(selected);
}
function actor(){const d=info[view],active=selectedGroup();return `${renderPageHeading('Actores y relaciones',d.title,d.desc)}<div class="actor-layout"><aside class="actor-index" aria-label="Temas de ${d.core}">${d.resource?`<div class="actor-resource"><span class="mini-label">${d.resource[0]}</span><button class="resource-link ${selected===d.resource[2]?'active':''}" data-detail="${d.resource[2]}">${icon('book')}<span>${d.resource[1]}</span><span aria-hidden="true">↗</span></button></div>`:''}<nav aria-label="Categorías">${d.groups.map((g,i)=>`<div class="index-group ${active?.id===g.id?'is-active':''}"><button class="group-link" ${g.go?`data-go="${g.go}"`:`data-detail="${g.id}" aria-expanded="${active?.id===g.id}"`}><span class="group-number">0${i+1}</span><span><strong>${g.title}</strong><small>${g.subtitle}</small></span><span class="group-arrow" aria-hidden="true">${g.go?'↗':active?.id===g.id?'−':'+'}</span></button>${active?.id===g.id&&g.children.length?`<div class="sub-index">${g.children.map(c=>`<button class="${selected===c[0]?'active':''}" data-detail="${c[0]}" ${selected===c[0]?'aria-current="true"':''}>${icon(c[2])}<span>${c[1]}</span></button>`).join('')}</div>`:''}</div>`).join('')}</nav></aside><section class="detail actor-detail" tabindex="-1" aria-live="polite">${detailContent()}</section></div>`;}
function safeURL(s){try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.href:null}catch{return null}}
function docs(id){const list=(window.ISF_EJEMPLOS[id]||[]).filter(d=>safeURL(d.url));return `<div class="documents"><span class="mini-label">Documentos de ejemplo</span>${list.length?list.map(d=>`<a class="document-link" href="${esc(safeURL(d.url))}" target="_blank" rel="noopener noreferrer">${icon('file')}<div>${esc(d.titulo)} ↗<span>${esc(d.descripcion)}</span></div></a>`).join(''):'<p class="empty-docs">Aún no hay documentos vinculados a esta etapa.</p>'}</div>`}
function cycle(){const s=ISF.etapas[stage];return `${renderPageHeading('Método común · decisiones verificables','El ciclo de una intervención','Cada etapa genera antecedentes para decidir el siguiente paso.',`<button class="quiet example-toggle" id="example" aria-pressed="${example}">${example?'Cerrar ejemplo':'Abrir ejemplo hídrico'}</button>`)}<div class="cycle-nav" aria-label="Etapas">${ISF.etapas.map((s,i)=>`<button class="stage-btn ${stage===i?'active':''}" data-stage="${i}" aria-pressed="${stage===i}">${icon(s.icono)}<span class="num">0${i+1}</span><strong>${s.titulo}</strong></button>`).join('')}</div><div class="stage-content"><div><span class="mini-label">${s.titulo}</span><h2>${s.pregunta}</h2><p>${s.accion}</p><span class="mini-label">Quiénes participan</span><p class="muted">${s.actores}</p><div class="checkpoint"><span class="mini-label">Decisión o condición para avanzar</span><p>${s.control}</p></div></div><div><span class="mini-label">Qué deja esta etapa</span><p>${s.producto}</p>${docs(s.id)}</div></div>${example?`<div class="example-band"><strong>Ejemplo ilustrativo · una comunidad con dificultades de acceso al agua</strong><p>${s.ejemplo}</p><p class="small">Sin comunidad, solución ni beneficiarios comprometidos. El caso se desarrolla al cambiar de etapa.</p></div>`:''}<div class="transverse">${icon('school')}<div><strong>Fortalecimiento de capacidades durante el proceso.</strong> Participación, talleres y materiales de apoyo preparan a la comunidad para operar, mantener la solución y afrontar otros desafíos.</div></div>`}
function defined(){return `${renderPageHeading('Por qué la selección es progresiva','Un método definido desde el inicio','La selección, la prefactibilidad y el diagnóstico forman parte de la intervención y requieren recursos profesionales y trabajo en terreno.')}<div class="comparison"><article><span class="eyebrow">Definido en el programa</span><h2>Compromisos y controles</h2><ul><li>12 intervenciones en 36 meses y 5 regiones.</li><li>Meta de al menos 1.920 beneficiarios directos.</li><li>Criterios de elegibilidad y priorización.</li><li>Metodología, equipo y presupuesto.</li><li>Productos, indicadores y trazabilidad.</li><li>Antecedentes técnicos y legales antes de implementar.</li></ul></article><article><span class="eyebrow">Definido con el territorio</span><h2>Comunidad y solución pertinente</h2><ul><li>Qué comunidad cumple los criterios y se prioriza.</li><li>Cuál es la carencia y cuáles son sus causas.</li><li>A cuántas personas beneficiará efectivamente.</li><li>Qué alternativa técnica responde al diagnóstico.</li><li>Qué permisos y antecedentes necesita esa solución.</li><li>Qué meta técnica permitirá comprobar el resultado.</li></ul></article></div><p class="closing">La obra es el resultado de una evaluación técnica y comunitaria. Seleccionar progresivamente permite descartar intervenciones inviables y orientar la implementación a soluciones pertinentes.</p><button class="text-link" data-go="ciclo">Revisar cómo se documenta cada decisión →</button>`}
function results(){return `${renderPageHeading('Cómo sabemos si funcionó','Resultados técnicos y comunitarios','La evaluación combina desempeño de la solución, percepción de las personas y capacidades para sostenerla.')}<div class="results">${[['12','Intervenciones','Mejoras en calidad y/o acceso a servicios básicos.'],['1.920','Beneficiarios directos','Meta mínima del programa, con población verificada por intervención.'],['≥90%','Funcionamiento y meta técnica','Soluciones operativas al cierre que cumplen la meta técnica definida.'],['≥80%','Satisfacción','Personas encuestadas satisfechas o muy satisfechas con la situación posterior.'],['≥90%','Capacidades para la continuidad','Comunidades con responsables capacitados y plan de operación y mantenimiento.'],['≤$148.125','Costo por beneficiario','Costo total ejecutado del programa dividido por beneficiarios directos.']].map(a=>`<article class="result"><strong>${a[0]}</strong><h3>${a[1]}</h3><p>${a[2]}</p></article>`).join('')}</div><button class="text-link" data-modal="otros">Otros compromisos del formulario: género y beneficio económico</button>`}
function render(focus=false){$('#app').innerHTML=`<div class="page">${view==='inicio'?home():view==='intervencion'?intervention():info[view]?actor():view==='ciclo'?cycle():view==='definido'?defined():results()}</div>`;const trail=view==='inicio'?['inicio']:view==='intervencion'?['inicio','intervencion']:view==='ciclo'&&cycleParent==='isf'?['inicio','intervencion','isf','ciclo']:view==='resultados'&&resultsParent==='inicio'?['inicio','resultados']:['inicio','intervencion',view];$('#crumbs').innerHTML=trail.map((v,i)=>i===trail.length-1?`<span aria-current="page">${labels[v]}</span>`:`<button data-go="${v}">${labels[v]}</button><span aria-hidden="true">/</span>`).join('');const i=sequence.indexOf(view);$('#position').textContent=`${String(i+1).padStart(2,'0')} / 08`;$('#back').hidden=view==='inicio';$('#next').textContent=i===7?'Volver al programa ↺':view==='inicio'?'Explorar una intervención →':`Continuar: ${labels[sequence[i+1]]} →`;if(focus){$('#app').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})}}
function go(v,hash=true){if(!sequence.includes(v))return;if(v==='ciclo'&&view!=='ciclo')cycleParent=view==='isf'?'isf':'intervencion';if(v==='resultados'&&view!=='resultados')resultsParent=view==='inicio'?'inicio':'intervencion';view=v;if(info[v])selected=info[v].groups[0].id;if(hash&&location.hash.slice(1)!==v)location.hash=v;render(true)}
function openModal(type){const m={alcance:`<h2 id="modal-title">Alcance y recursos del programa</h2><p><strong>5 regiones:</strong> ${ISF.regiones.join(', ')}.</p><p>Se espera intervenir al menos una comunidad en cada región. La planificación contempla cuatro intervenciones por año.</p><p><strong>1.920 personas:</strong> 12 intervenciones × promedio referencial de 160 beneficiarios. La cantidad puede variar entre comunidades y se verifica en el diagnóstico.</p><p><strong>Presupuesto total:</strong> $284.400.000.<br>Donaciones solicitadas: $264.400.000.<br>Aporte propio: $20.000.000.</p><p><strong>Ejecución física:</strong> $96.000.000 en tres años, con un promedio de $8.000.000 por intervención.</p><p class="small">Fuente: formulario de postulación, versión 20-09(1). El programa comprende servicios básicos; este recorrido profundiza en agua y saneamiento.</p>`,otros:`<h2 id="modal-title">Otros compromisos del formulario</h2><h3>Participación de mujeres</h3><p>Asegurar una participación representativa en el diseño participativo y la toma de decisiones. El formulario contempla medir la participación en sesiones o en roles de decisión.</p><h3>Beneficio económico</h3><p>Generar en promedio al menos $2.000.000 anuales en beneficios económicos o ahorros por intervención implementada.</p><p class="small">Se calcula como la suma de beneficios económicos y/o ahorros anuales estimados dividida por las intervenciones evaluadas. Se mantiene este compromiso porque figura en el PDF de referencia.</p>`};$('#modal-body').innerHTML=m[type];$('#modal').showModal()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.go){const r=b.getBoundingClientRect(),m=$('#app').getBoundingClientRect();$('#app').style.setProperty('--zoom-origin',`${r.x+r.width/2-m.x}px ${r.y+r.height/2-m.y}px`);go(b.dataset.go);}if(b.dataset.detail){selected=b.dataset.detail;render();if(innerWidth<701){$('.detail').focus({preventScroll:true});$('.detail').scrollIntoView({behavior:'smooth',block:'start'})}else{document.querySelector('[data-detail="'+selected+'"]')?.focus({preventScroll:true})}}if(b.dataset.stage!==undefined){stage=Number(b.dataset.stage);render()}if(b.dataset.modal)openModal(b.dataset.modal);if(b.id==='example'){example=!example;render();$('#example').focus()}if(b.id==='next')go(sequence[(sequence.indexOf(view)+1)%sequence.length]);if(b.id==='back')go(view==='ciclo'?cycleParent:view==='resultados'?resultsParent:info[view]||['definido','resultados'].includes(view)?'intervencion':'inicio');if(b.classList.contains('close'))$('#modal').close();if(b.id==='fullscreen'){if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen?.().catch(()=>{});}});
document.addEventListener('fullscreenchange',()=>$('#fullscreen').textContent=document.fullscreenElement?'Salir de pantalla completa':'Pantalla completa');
document.addEventListener('keydown',e=>{if($('#modal').open||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='Escape'){e.preventDefault();$('#back').click()}if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const delta=e.key==='ArrowRight'?1:-1;if(view==='ciclo'&&stage+delta>=0&&stage+delta<ISF.etapas.length){stage+=delta;render()}else go(sequence[Math.max(0,Math.min(sequence.length-1,sequence.indexOf(view)+delta))]);}});
window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(sequence.includes(v)&&v!==view)go(v,false)});
window.addEventListener('message',e=>{if(e.source!==window.parent||window.parent===window)return;if(e.data?.type==='isf-ejemplos-preview'&&e.data.ejemplos){window.ISF_EJEMPLOS=e.data.ejemplos;if(Number.isInteger(e.data.stage))stage=Math.max(0,Math.min(6,e.data.stage));view='ciclo';render()}});
go(sequence.includes(location.hash.slice(1))?location.hash.slice(1):'inicio',false);

})();
