/* Contenido de la presentación. Fuente principal: Anexo A, versión 20-09(1).
   Edite textos y cifras aquí; los documentos de ejemplo van en ejemplos.js. */
window.ISF = {
 nombre: 'Proyectos de Ingeniería Humanitaria para el Desarrollo Sostenible de Comunidades Vulnerables',
 regiones: ['Coquimbo','Valparaíso','Metropolitana','Biobío','Araucanía'],
 etapas: [
 {id:'identificacion',titulo:'Identificación territorial',icono:'pin',pregunta:'¿Dónde hace falta apoyo técnico?',accion:'ISF identifica potenciales comunidades junto a municipios, SLEP, universidades y organizaciones con presencia local.',actores:'ISF · redes territoriales · posibles contrapartes comunitarias',producto:'Cartera de potenciales intervenciones y antecedentes territoriales.',control:'Identificar una comunidad abre una evaluación; todavía no implica seleccionarla.',ejemplo:'Una red territorial informa que un sector tiene dificultades recurrentes para acceder al agua.'},
 {id:'elegibilidad',titulo:'Elegibilidad',icono:'check',pregunta:'¿Existen condiciones básicas para trabajar juntos?',accion:'Se verifica una contraparte organizada y dispuesta a participar, vulnerabilidad y carencia de servicios comprobables, y viabilidad legal inicial para intervenir.',actores:'ISF · contraparte local · entidades que aportan antecedentes',producto:'Ficha de elegibilidad con antecedentes de organización, vulnerabilidad, carencia y situación legal.',control:'Los tres requisitos deben cumplirse. Las restricciones críticas llevan a descartar la candidatura e informar a las partes.',ejemplo:'Se verifica la organización local, la carencia hídrica y quién administra el terreno o la infraestructura.'},
 {id:'prefactibilidad',titulo:'Prefactibilidad y priorización',icono:'compass',pregunta:'¿Es una intervención necesaria, viable y sostenible?',accion:'Se comparan necesidad e impacto, vulnerabilidad y género, organización y sostenibilidad, factibilidad técnica y económica, viabilidad normativa, riesgos y logística.',actores:'ISF · coordinación territorial · comunidad · apoyos técnicos pertinentes',producto:'Informe de prefactibilidad y matriz de priorización con variables y ponderaciones definidas.',control:'La selección se documenta. Se descartan a tiempo alternativas inviables para reducir riesgos y orientar los recursos.',ejemplo:'Se revisan posibles causas, costos preliminares, permisos, riesgos y condiciones para mantener una futura solución.'},
 {id:'diagnostico',titulo:'Diagnóstico comunitario',icono:'search',pregunta:'¿Cuál es el problema y a quién afecta?',accion:'La comunidad y el equipo conocen el territorio, sus recursos, sueños y desafíos. Se levantan antecedentes técnicos y sociales para comprender las causas y establecer la situación inicial.',actores:'Comunidad · coordinación territorial · voluntariado y practicantes',producto:'Informe de diagnóstico, caracterización de beneficiarios y antecedentes de la carencia específica.',control:'Al terminar el diagnóstico e iniciar el diseño se confirma la población directamente beneficiada, evitando duplicaciones.',ejemplo:'Se examinan almacenamiento, presión, continuidad y condiciones sanitarias; se registra cuándo y a quiénes afectan las fallas.'},
 {id:'diseno',titulo:'Diseño participativo',icono:'ruler',pregunta:'¿Qué solución responde mejor al desafío?',accion:'Comunidad, equipo técnico y mentores proponen, comparan y refinan alternativas hasta llegar a una propuesta validada en terreno. Se define una meta técnica apropiada al problema.',actores:'Comunidad · ISF · voluntariado · mentores profesionales',producto:'Diseño, presupuesto, meta técnica y plan de trabajo. Expediente técnico y legal según la obra.',control:'Antes de implementar: autorización, antecedentes de propiedad o uso, descripción técnica, presupuesto, croquis o planos y permisos aplicables.',ejemplo:'Se comparan alternativas de almacenamiento, distribución o tratamiento según las causas verificadas y la capacidad de operación local.'},
 {id:'implementacion',titulo:'Implementación',icono:'tool',pregunta:'¿Cómo hacemos realidad la solución acordada?',accion:'Se ejecuta el plan construido con la comunidad, con objetivos, responsables y equipos definidos. Se integran materiales, trabajo comunitario y contrataciones especializadas según corresponda.',actores:'Comunidad · coordinación territorial · equipo técnico · especialistas',producto:'Solución implementada, informe de implementación y antecedentes de recepción o puesta en marcha.',control:'La ejecución debe responder al diseño acordado y contar previamente con los antecedentes técnicos y legales que correspondan.',ejemplo:'Se implementa la alternativa seleccionada, se realizan pruebas y se capacita a los responsables de su operación.'},
 {id:'evaluacion',titulo:'Cierre y evaluación',icono:'chart',pregunta:'¿Funciona y existen capacidades para sostenerla?',accion:'Se verifica el funcionamiento y la meta técnica, se recoge la percepción comunitaria y se revisan responsables capacitados y plan de operación y mantenimiento.',actores:'ISF · comunidad · equipo de intervención',producto:'Informe de evaluación, mediciones técnicas, encuesta de satisfacción y registros de capacitación.',control:'Metas del programa: ≥90% de soluciones operativas y con meta técnica cumplida; ≥80% de satisfacción; ≥90% de comunidades con responsables capacitados y plan de mantenimiento.',ejemplo:'Se comparan las condiciones iniciales y finales del servicio y se comprueba que los responsables conocen el plan de operación.'}
 ],
 desafios: [
 {id:'continuidad',titulo:'Acceso y continuidad',icono:'drop',resumen:'Agua que no llega o no está disponible cuando se necesita.',detalles:['Interrupciones del suministro o dependencia de entregas externas.','Presión insuficiente o distribución que no llega a los puntos de uso.','Tiempo y esfuerzo que las familias dedican a conseguir agua.'],investigar:'Disponibilidad, horarios, presión, puntos de abastecimiento y población afectada.',medir:'Horas de disponibilidad, interrupciones o presión, según la meta definida en el diseño.'},
 {id:'calidad',titulo:'Calidad y almacenamiento',icono:'tank',resumen:'Condiciones que pueden afectar la cantidad o seguridad del agua almacenada.',detalles:['Capacidad de almacenamiento insuficiente.','Estanques expuestos o con dificultades de limpieza.','Posibles fuentes de contaminación que requieren verificación técnica.'],investigar:'Capacidad útil, estado de estanques, manejo del agua y parámetros de calidad pertinentes.',medir:'Capacidad disponible o parámetros de calidad, según el diagnóstico y el diseño.'},
 {id:'saneamiento',titulo:'Saneamiento',icono:'waves',resumen:'Dificultades para manejar y tratar las aguas residuales.',detalles:['Evacuación o tratamiento insuficiente de aguas servidas.','Exposición a descargas, malos olores o contacto con aguas residuales.','Sistemas que no responden a las condiciones del suelo o a la capacidad de operación.'],investigar:'Infraestructura existente, descargas, condiciones del terreno y requisitos aplicables.',medir:'Desempeño y funcionamiento del sistema conforme a la solución diseñada.'},
 {id:'gestion',titulo:'Operación y mantenimiento',icono:'tool',resumen:'Capacidades y recursos necesarios para sostener el servicio.',detalles:['Responsables y funciones poco definidos.','Falta de herramientas, capacitación o plan de mantenimiento.','Costos de operación que dificultan la continuidad de una solución.'],investigar:'Organización, conocimientos, recursos, costos y prácticas de mantenimiento.',medir:'Responsables capacitados y existencia de un plan de operación y mantenimiento.'}
 ]
};
