const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const original=JSON.parse(JSON.stringify(window.ISF_EJEMPLOS));let data=JSON.parse(JSON.stringify(original)),stage=0,storage=true;
try{const saved=JSON.parse(localStorage.getItem('isf-ejemplos-borrador-v1')||'null');if(saved&&ISF.etapas.every(s=>Array.isArray(saved[s.id])))data=saved;}catch{storage=false;}
const select=document.querySelector('#stage'),entries=document.querySelector('#entries'),status=document.querySelector('#status'),frame=document.querySelector('#preview');
select.innerHTML=ISF.etapas.map((s,i)=>`<option value="${i}">${i+1}. ${s.titulo}</option>`).join('');
function validURL(url){try{return ['https:','http:'].includes(new URL(url).protocol)}catch{return false}}
function preview(){frame.contentWindow.postMessage({type:'isf-ejemplos-preview',ejemplos:data,stage},'*')}
function save(){try{localStorage.setItem('isf-ejemplos-borrador-v1',JSON.stringify(data))}catch{storage=false}status.textContent=storage?'Borrador guardado en este navegador. Descarga el archivo para compartirlo.':'Descarga el archivo para conservar los cambios; el navegador no permite guardar un borrador.';preview()}
function render(){entries.innerHTML=(data[ISF.etapas[stage].id]||[]).map((e,i)=>`<article class="entry"><label for="title-${i}">Título del documento ${i+1}</label><input id="title-${i}" data-index="${i}" data-field="titulo" value="${escapeHTML(e.titulo)}"><label for="description-${i}">Descripción breve</label><textarea id="description-${i}" data-index="${i}" data-field="descripcion">${escapeHTML(e.descripcion)}</textarea><label for="url-${i}">Enlace</label><input id="url-${i}" type="url" data-index="${i}" data-field="url" value="${escapeHTML(e.url)}" placeholder="https://…" aria-describedby="error-${i}"><p id="error-${i}" class="error">${e.url&&!validURL(e.url)?'Usa un enlace completo que comience con https:// o http://.':''}</p><button class="remove" data-remove="${i}">Quitar documento ${i+1}</button></article>`).join('');preview()}
entries.addEventListener('input',e=>{if(e.target.dataset.index===undefined)return;const i=Number(e.target.dataset.index),field=e.target.dataset.field;data[ISF.etapas[stage].id][i][field]=e.target.value;if(field==='url'){const invalid=e.target.value&&!validURL(e.target.value);document.querySelector(`#error-${i}`).textContent=invalid?'Usa un enlace completo que comience con https:// o http://.':'';e.target.setAttribute('aria-invalid',Boolean(invalid))}save()});
entries.addEventListener('click',e=>{if(e.target.dataset.remove!==undefined){data[ISF.etapas[stage].id].splice(Number(e.target.dataset.remove),1);save();render()}});
select.addEventListener('change',()=>{stage=Number(select.value);render()});
document.querySelector('#add').addEventListener('click',()=>{data[ISF.etapas[stage].id].push({titulo:'',descripcion:'',url:''});save();render();entries.lastElementChild?.querySelector('input').focus()});
document.querySelector('#download').addEventListener('click',()=>{const invalid=Object.values(data).flat().some(d=>d.url&&(!validURL(d.url)||!d.titulo.trim()));if(invalid){status.textContent='Revisa los enlaces y agrega un título a cada documento vinculado antes de descargar.';return}const text='/* Ejemplos asociados a las etapas de la metodología ISF. Editar con editor.html. */\nwindow.ISF_EJEMPLOS = '+JSON.stringify(data,null,2)+';\n';const url=URL.createObjectURL(new Blob([text],{type:'text/javascript;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='ejemplos.js';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Archivo descargado. Reemplaza ejemplos.js en la carpeta y recarga la presentación.';});
document.querySelector('#reset').addEventListener('click',()=>{if(confirm('¿Restaurar los ejemplos del archivo original y descartar el borrador de este navegador?')){data=JSON.parse(JSON.stringify(original));save();render();status.textContent='Se restauraron los datos del archivo ejemplos.js.'}});
frame.addEventListener('load',preview);render();
